// Списка заказов
export const ORDERS_ORDERS_FETCH = 'ORDERS_ORDERS_FETCH';
export const ORDERS_ORDERS_SUCCESS = 'ORDERS_ORDERS_SUCCESS';
export const ORDERS_ORDERS_FAIL = 'ORDERS_ORDERS_FAIL';

// История заказов
export const ORDERS_ORDERS_HISTORY_FETCH = 'ORDERS_ORDERS_HISTORY_FETCH';
export const ORDERS_ORDERS_HISTORY_SUCCESS = 'ORDERS_ORDERS_HISTORY_SUCCESS';
export const ORDERS_ORDERS_HISTORY_FAIL = 'ORDERS_ORDERS_HISTORY_FAIL';

// Заказ
export const ORDERS_ORDER_FETCH = 'ORDERS_ORDER_FETCH';
export const ORDERS_ORDER_SUCCESS = 'ORDERS_ORDER_SUCCESS';
export const ORDERS_ORDER_FAIL = 'ORDERS_ORDER_FAIL';

// Принятие заказа
export const ORDERS_ORDER_ACCEPT_FETCH = 'ORDERS_ORDER_ACCEPT_FETCH';
export const ORDERS_ORDER_ACCEPT_SUCCESS = 'ORDERS_ORDER_ACCEPT_SUCCESS';
export const ORDERS_ORDER_ACCEPT_FAIL = 'ORDERS_ORDER_ACCEPT_FAIL';

// Заказ в пути
export const ORDERS_ORDER_IN_WAY_FETCH = 'ORDERS_ORDER_IN_WAY_FETCH';
export const ORDERS_ORDER_IN_WAY_SUCCESS = 'ORDERS_ORDER_IN_WAY_SUCCESS';
export const ORDERS_ORDER_IN_WAY_FAIL = 'ORDERS_ORDER_IN_WAY_FAIL';

// Завершение заказа
export const ORDERS_ORDER_COMPLETE_FETCH = 'ORDERS_ORDER_COMPLETE_FETCH';
export const ORDERS_ORDER_COMPLETE_SUCCESS = 'ORDERS_ORDER_COMPLETE_SUCCESS';
export const ORDERS_ORDER_COMPLETE_FAIL = 'ORDERS_ORDER_COMPLETE_FAIL';

// Отмена заказа
export const ORDERS_ORDER_CANCEL_FETCH = 'ORDERS_ORDER_CANCEL_FETCH';
export const ORDERS_ORDER_CANCEL_SUCCESS = 'ORDERS_ORDER_CANCEL_SUCCESS';
export const ORDERS_ORDER_CANCEL_FAIL = 'ORDERS_ORDER_CANCEL_FAIL';

// Открепится от заказа
export const ORDERS_ORDER_DETACH_FETCH = 'ORDERS_ORDER_DETACH_FETCH';
export const ORDERS_ORDER_DETACH_SUCCESS = 'ORDERS_ORDER_DETACH_SUCCESS';
export const ORDERS_ORDER_DETACH_FAIL = 'ORDERS_ORDER_DETACH_FAIL';

// Обновление заказа
export const ORDERS_ORDER_UPDATE_FETCH = 'ORDERS_ORDER_UPDATE_FETCH';
export const ORDERS_ORDER_UPDATE_SUCCESS = 'ORDERS_ORDER_UPDATE_SUCCESS';
export const ORDERS_ORDER_UPDATE_FAIL = 'ORDERS_ORDER_UPDATE_FAIL';

// Список заказов в фоновом режиме
export const ORDERS_ORDERS_LONGPOLL_START = 'ORDERS_ORDERS_LONGPOLL_START';
export const ORDERS_ORDERS_LONGPOLL_STOP = 'ORDERS_ORDERS_LONGPOLL_STOP';

// Поделится по whatsapp
export const ORDERS_ORDER_WHATSAPP_SHARE = 'ORDERS_ORDER_WHATSAPP_SHARE';
