// Список уведомлений
export const NOTICES_NOTICES_FETCH = 'NOTICES_NOTICES_FETCH';
export const NOTICES_NOTICES_SUCCESS = 'NOTICES_NOTICES_SUCCESS';
export const NOTICES_NOTICES_FAIL = 'NOTICES_NOTICES_FAIL';

// Прочитать все
export const NOTICES_NOTICES_READED_FETCH = 'NOTICES_NOTICES_READED_FETCH';
export const NOTICES_NOTICES_READED_SUCCESS = 'NOTICES_NOTICES_READED_SUCCESS';
export const NOTICES_NOTICES_READED_FAIL = 'NOTICES_NOTICES_READED_FAIL';
