// Список приглашений
export const DRIVERS_INVITES_FETCH = 'DRIVERS_INVITES_FETCH';
export const DRIVERS_INVITES_SUCCESS = 'DRIVERS_INVITES_SUCCESS';
export const DRIVERS_INVITES_FAIL = 'DRIVERS_INVITES_FAIL';

// Принять приглашение
export const DRIVERS_INVITE_ACCEPT_FETCH = 'DRIVERS_INVITE_ACCEPT_FETCH';
export const DRIVERS_INVITE_ACCEPT_SUCCESS = 'DRIVERS_INVITE_ACCEPT_SUCCESS';
export const DRIVERS_INVITE_ACCEPT_FAIL = 'DRIVERS_INVITE_ACCEPT_FAIL';
