// Получить список операций
export const BILLING_OPERATIONS_FETCH = 'BILLING_OPERATIONS_FETCH';
export const BILLING_OPERATIONS_SUCCESS = 'BILLING_OPERATIONS_SUCCESS';
export const BILLING_OPERATIONS_FAIL = 'BILLING_OPERATIONS_FAIL';
