// Служба
export const SUPPLIERS_SUPPLIER_FETCH = 'SUPPLIERS_SUPPLIER_FETCH';
export const SUPPLIERS_SUPPLIER_SUCCESS = 'SUPPLIERS_SUPPLIER_SUCCESS';
export const SUPPLIERS_SUPPLIER_FAIL = 'SUPPLIERS_SUPPLIER_FAIL';

// Обновление службы
export const SUPPLIERS_SUPPLIER_UPDATE_FETCH = 'SUPPLIERS_SUPPLIER_UPDATE_FETCH';
export const SUPPLIERS_SUPPLIER_UPDATE_SUCCESS = 'SUPPLIERS_SUPPLIER_UPDATE_SUCCESS';
export const SUPPLIERS_SUPPLIER_UPDATE_FAIL = 'SUPPLIERS_SUPPLIER_UPDATE_FAIL';
